src/infiniop/devices/handle.cc
src/infiniop/devices/maca/common_maca.h
src/infiniop/devices/maca/maca_handle.cc
src/infiniop/devices/maca/maca_handle.h
src/infiniop/ops/matmul/maca/matmul_maca.cc
src/infiniop/ops/matmul/maca/matmul_maca.h
src/infiniop/ops/matmul/operator.cc
src/infinirt/maca/infinirt_maca.cc
src/infinirt/maca/infinirt_maca.h
test/infiniop/libinfiniop/utils.py
xmake.lua
xmake/maca.lua

issue/87/feat:增加沐曦平台的handle

---

.github/workflows/build.yml
include/infiniop/ops/random_sample.h
src/infiniop/ops/random_sample/cpu/random_sample_cpu.cc
src/infiniop/ops/random_sample/cpu/random_sample_cpu.h
src/infiniop/ops/random_sample/operator.cc
src/infiniop/ops/random_sample/random_sample.h
src/utils/check.h
test/infiniop/random_sample.py

issue/48: random sample 算子 - CPU

---

src/infiniop/ops/gemm/cpu/gemm_cpu.cc

目前在寒武纪590（docker），英伟达A100（裸机），昇腾.8（裸机），沐曦.17（裸机），摩尔.101（docker），计算所昆仑芯（docker）通过测试

issue/130: GEMM算子CPU平台的omp重构

---

src/infiniop/devices/maca/common_maca.h
src/infiniop/devices/maca/maca_handle.cc
src/infiniop/ops/rms_norm/maca/rms_norm_maca.cuh
src/infiniop/ops/rms_norm/maca/rms_norm_maca.maca
src/infiniop/ops/rms_norm/operator.cc
xmake/maca.lua

issue/40: 实现沐曦rms_norm算子

---

src/infiniop/devices/ascend/common_ascend.cc
src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.h
src/infiniop/ops/causal_softmax/operator.cc
src/infiniop/ops/swiglu/operator.cc
test/infiniop/causal_softmax.py

issue/8: causalsoftmax算子-昇腾

---

src/infiniop-test/include/ops.hpp
src/infiniop-test/src/ops/swiglu.cpp
test/infiniop-test/test_generate/testcases/swiglu.py

添加swiglu算子测例

---

src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
src/infiniop/ops/gemm/ascend/gemm_ascend.cc
src/infiniop/ops/rms_norm/ascend/rms_norm_aclnn.cc

针对aclSetAclOpExecutorRepeatable函数（https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/800alpha003/apiref/aolapi/operatorlist_00041.html）
的约束限制，并且昇腾官方人员并没有给出不能调用此函数的aclnn算子统计列表，因此此函数成为了带有潜在危险的函数，目前已在rearrange算子调用aclnnInplaceCopy暴露出问题
为了解决上述问题，将现有的昇腾调库算子改为在calculate阶段统一调用getworkspace算子重新生成新的executor
当遇到不得不使能executor复用的情况，如calculate阶段存在for循环调用计算算子，则添加CHECK_ACL()检查，防止后续版本会报出问题

修复昇腾调用aclSetAclOpExecutorRepeatable的潜在危险

---

test/infiniop/add.py
test/infiniop/swiglu.py

- Fix the issue #200 
- Update FP16 tolerance values to better reflect their precision.

Issue/200/fix: Updata FP16 and FP32 Tolerance for Add and SwiGLU

---

README.md
src/infiniop/ops/random_sample/cpu/random_sample_cpu.cc
src/infiniop/ops/random_sample/cuda/random_sample_cuda.cu
src/infiniop/ops/random_sample/cuda/random_sample_cuda.cuh
src/infiniop/ops/random_sample/cuda/random_sample_kernel.cuh
src/infiniop/ops/random_sample/info.h
src/infiniop/ops/random_sample/operator.cc
src/infiniop/ops/random_sample/random_sample.h

issue/191/docs: 规范 random sample 算子构造过程，添加 cuda 接口

---

src/infiniop/ops/causal_softmax/maca/causal_softmax_kernel.h
src/infiniop/ops/causal_softmax/maca/causal_softmax_maca.h
src/infiniop/ops/causal_softmax/maca/causal_softmax_maca.maca
src/infiniop/ops/causal_softmax/operator.cc
src/infiniop/reduce/maca/reduce.h

issue/39 Migrate cuda causal softmax to metax

---

src/infiniop/ops/rearrange/maca/rearrange_kernel.h
src/infiniop/ops/rearrange/maca/rearrange_maca.h
src/infiniop/ops/rearrange/maca/rearrange_maca.maca
src/infiniop/ops/rearrange/operator.cc

issue/238 - Migrate cuda rearrange to metax

---

src/infiniop/ops/random_sample/maca/random_sample_kernel.h
src/infiniop/ops/random_sample/maca/random_sample_maca.h
src/infiniop/ops/random_sample/maca/random_sample_maca.maca
src/infiniop/ops/random_sample/operator.cc

issue/36 - Migrate cuda ramdom sample to metax

issue/36 - Migrate cuda ramdom sample to metax

---

test/infiniop/libinfiniop/utils.py

- fix the issue #273, which is cannot correctly print out the discrepancy when one is NaN. 
- Further support the `equal_nan` option for `debug()` and `debug_all()`

issue/273: Fully Support `equal_nan` Option for `debug()` and `debug_all()`

---

include/infiniop.h
include/infiniop/ops/add.h
include/infiniop/ops/sub.h
scripts/python_test.py
src/infiniop-test/include/ops.hpp
src/infiniop-test/src/ops/sub.cpp
src/infiniop/ops/sub/cpu/sub_cpu.cc
src/infiniop/ops/sub/cpu/sub_cpu.h
src/infiniop/ops/sub/cuda/sub_cuda.cu
src/infiniop/ops/sub/cuda/sub_cuda.cuh
src/infiniop/ops/sub/cuda/sub_cuda_internal.cuh
src/infiniop/ops/sub/operator.cc
test/infiniop-test/test_generate/testcases/sub.py
test/infiniop/sub.py

添加了Sub算子的头文件、cpu实现、cuda实现、python测试用例、gguf测试用例
resolves #205

issue/205 - 添加Sub算子 resolves #205

---

test/infiniop/gemm.py
test/infiniop/random_sample.py
test/infiniop/rearrange.py

- Improve the compatibility of the PyTorch implementations of gemm and random sample
- fix typo in rearrange.py

issue/288: Improve the Compatibility of the Torch Implementations

---

README.md
src/infiniop/devices/cuda/cuda_common.cu
src/infiniop/devices/cuda/cuda_kernel_common.cuh
src/infiniop/ops/causal_softmax/cuda/causal_softmax_cuda.cu
src/infiniop/ops/clip/cuda/clip_cuda_internal.cuh
src/infiniop/ops/gemm/cuda/gemm_cuda.cu
src/infiniop/ops/gemm/info.h
src/infiniop/ops/rearrange/cuda/rearrange_kernel.cuh
src/infiniop/ops/rms_norm/cuda/rms_norm_cuda.cu
src/infinirt/cuda/infinirt_cuda.cu
xmake.lua
xmake/iluvatar.lua

用这个命令测试：
```shell
python ./scripts/python_test.py --nvidia
```
都能过

issue/158/feat: 支持天数

---

test/infiniop-test/test_generate/testcases/cross_entropy_loss_backward.py
test/infiniop-test/test_generate/testcases/div.py
test/infiniop-test/test_generate/testcases/equal.py
test/infiniop-test/test_generate/testcases/gelu.py
test/infiniop-test/test_generate/testcases/gelu_backward.py
test/infiniop-test/test_generate/testcases/logical_and.py
test/infiniop-test/test_generate/testcases/logical_or.py
test/infiniop-test/test_generate/testcases/relu_backward.py
test/infiniop-test/test_generate/testcases/silu.py

Add scripts to generate gguf test cases for Question 2.

---

test/infiniop-test/test_generate/infiniop_test.py

issue/356 - fixed a type error

---

test/infiniop-test/test_generate/infiniop_test.py
test/infiniop-test/test_generate/testcases/cross_entropy_loss_backward.py
test/infiniop-test/test_generate/testcases/div.py
test/infiniop-test/test_generate/testcases/equal.py
test/infiniop-test/test_generate/testcases/gelu.py
test/infiniop-test/test_generate/testcases/gelu_backward.py
test/infiniop-test/test_generate/testcases/logical_and.py
test/infiniop-test/test_generate/testcases/logical_or.py
test/infiniop-test/test_generate/testcases/relu_backward.py
test/infiniop-test/test_generate/testcases/silu.py

Add scripts to generate gguf test cases for T1-1-2

---

test/infiniop/libinfiniop/utils.py

issue/365 - fixing an interface mismatch

---

src/infiniop/devices/moore/moore_kernel_common.h
src/infiniop/elementwise/moore/elementwise_moore.h
src/infiniop/elementwise/moore/elementwise_moore_api.h
src/infiniop/ops/swiglu/moore/siwglu_moore_kernel.h
src/infiniop/ops/swiglu/moore/swiglu_moore.h
src/infiniop/ops/swiglu/moore/swiglu_moore.mu
src/infiniop/ops/swiglu/operator.cc

摩尔平台 Elementwise 及 Swiglu 算子实现

issue/246: add Elementwise and SwiGLU in moore gpu

---

src/infiniop/ops/rope/bang/rope_bang.h
src/infiniop/ops/rope/bang/rope_bang.mlu
src/infiniop/ops/rope/bang/rope_bang_kernel.mlu
src/infiniop/ops/rope/operator.cc

issue/265 - Implemented the RoPE operator for Cambricon Bang

---

src/infiniop/ops/rms_norm/kunlun/rms_norm_kunlun.xpu

p800 rmsnorm 3d

---

src/infiniop/ops/rope/kunlun/rope_kunlun.xpu

issue/466: 昆仑平台rope关于NEOX算法的实现

---

include/infiniop/ops/dequantize.h
src/infiniop/ops/dequantize/dequantize.h
src/infiniop/ops/dequantize/info.h
src/infiniop/ops/dequantize/nvidia/dequantize_w42f16_kernel.cuh
src/infiniop/ops/dequantize/nvidia/dequantize_w42f16_nvidia.cu
src/infiniop/ops/dequantize/operator.cc
test/infiniop/dequantize.py
test/infiniop/libinfiniop/op_register.py

1. 为 awq 量化添加 torch 实现，作为 python 测试 baseline
2. 重命名 NV 平台部分变量名及删除冗余函数参数，提升可读性

issue/458 : add AWQ dequantization torch test and improve variable naming readability
